### ISSUE TITLE
Leider geht es nicht

### ISSUE THREAD

**Issue by enrico73** [Nikba-Creative-Studio/WHMCS-Gateway-Fees-Addon#1]
Hi leider wird es nicht angezeigt im Warenkor. 
Muss man da noch weitere Einstellungen vornehmen?

Einstellungen unter Addons sind gemacht aber es wird nicht angezeigt 
Gruß Enrico

**Comment by Nikba-Creative-Studio** [comment]
Thank you for your message.

Please note that this addon is not designed to display anything in the shopping cart. It operates based on the payment method selected on the invoice page.

To activate and configure the module, please follow these steps:

1. Go to **System Settings** -> **Addon Modules**.
2. Activate the **Gateway Fees** addon.
3. After activation, click **Configure**.
4. You will see a list of payment methods available in your system.
5. You can configure the fee for a specific payment method, such as PayPal, and set the fee as a percentage or a custom value in currency.

<img width="100%" alt="Screenshot 2024-08-22 at 21 29 16" src="https://github.com/user-attachments/assets/69c36669-0e96-490e-87c3-d3d43fe6a70d">

Once configured, your clients will see the **Gateway VAT (Fee: +% or $)** when they select a payment method.

<img width="100%" alt="Screenshot 2024-08-22 at 21 26 40" src="https://github.com/user-attachments/assets/ab5f9aaf-aaa2-41df-9db5-7cc943c75c87">

**Comment by enrico73** [comment]
Ah ok. das wird nur auf der Rechnung angezeigt. Das müsste aber auch im Warenkorb angezeigt werden. Das wäre rechtlich besser. Kann man das ändern? 
Gruß Enrico

**Comment by Nikba-Creative-Studio** [comment]
Thank you for your suggestion
We will do our best to include this option in the next version. 
It would indeed be beneficial for the client to see the price at the moment of adding the product to the cart, depending on the payment method. 

Please send us your email address at office@nikba.com, and we will notify you about the update.

**Comment by enrico73** [comment]
cool. thank you ;o)

**Comment by enrico73** [comment]
TOP!!!!

**Comment by Nikba-Creative-Studio** [comment]
Dear [enrico73](https://github.com/enrico73),

We would like to inform you that, as per your request, we have implemented a new feature that displays fees for payment gateways on the Checkout page within the client interface. 
This feature has been tested with the default Twenty-One template in WHMCS.

<img width="100%" alt="Screenshot 2024-08-23 at 10 37 44" src="https://github.com/user-attachments/assets/06a6ee7f-1ec0-45a6-a801-d5c6169dc32a">

Please manually update the module to version 1.2, which includes the following changes:

1. **Currency Display Fix**:
   - The module now correctly displays fees in the default currency set in the WHMCS system. This fix ensures that all fees are shown in the appropriate currency without needing manual adjustments.

2. **Fee Display on Checkout Page for Twenty-One Template**:
   - Fees associated with payment methods configured via this module are now displayed on the checkout page when using the default Twenty-One template.
   - **Note for Developers**: If you are using a custom template, you might need to make adjustments to the `ShoppingCartCheckoutOutput` hook in the `hooks.php` file to ensure that fees are displayed correctly on the checkout page.
