### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by mrahmedinbox** [Nikba-Creative-Studio/WHMCS-Gateway-Fees-Addon#2]
hello, i 've installed it on v8.8 and php8.1, in addon configuration it show only usd not showing gbp and when configure the usd it doesn't show in invoices

**Comment by mrahmedinbox** [comment]
i used the stripe gateway

**Comment by mrahmedinbox** [comment]
it worked only for usd and on new invoices, i tried to edit already created invoice but the fees item not added

**Comment by Nikba-Creative-Studio** [comment]
Dear [mrahmedinbox](https://github.com/mrahmedinbox),

We kindly request you to update to version 1.2 of the module. This latest version resolves the issues related to static currency, ensuring that all fees are now displayed in the default currency set in your system.

<img width="100%" alt="Screenshot 2024-08-23 at 10 35 30" src="https://github.com/user-attachments/assets/d0135f6d-fcdc-4c49-8799-082b10a74a24">

Invoices that have already been created will not be modified unless you change the payment method to one that has a fee added by our module. This change can be made from the admin panel, the client interface, or the View Invoice page. When the payment method is changed, the fee will be added or removed accordingly.

<img width="100%" alt="Screenshot 2024-08-23 at 10 36 47" src="https://github.com/user-attachments/assets/6b9c6d48-f7f8-49e3-b6b2-7600f143fb6b">

We would also like to inform you that version 1.2 includes a new feature that displays fees on the Checkout page within the client account. This functionality has been tested exclusively with the Twenty-One Template. If you are using a different template, we recommend manually adjusting the ShoppingCartCheckoutOutput hook in the hooks.php file to ensure compatibility.

<img width="100%" alt="Screenshot 2024-08-23 at 10 37 44" src="https://github.com/user-attachments/assets/7411157a-1942-415c-815f-d108f70f6dd5">

**Comment by mrahmedinbox** [comment]
thanks for prompt update, can you make it cover all currencies enabled on system not only the main one ?

**Comment by Nikba-Creative-Studio** [comment]
Please manually update to version 1.2. In this version, all activated currencies in the system are supported. The user will see prices and fees in the currency that is set for them. If a specific currency is not set for a client, the price will be displayed in the default currency.

<img width="100%" alt="Screenshot 2024-08-24 at 11 37 28" src="https://github.com/user-attachments/assets/56afdd1e-2faf-42cb-9b59-1dd9f4e0166c">

**Client Checkout Page**

<img width="100%" alt="Screenshot 2024-08-24 at 11 37 59" src="https://github.com/user-attachments/assets/8ff79af8-86c9-419e-a81e-d411c24af592">

**Client Checkout Page**

<img width="100%" alt="Screenshot 2024-08-24 at 11 38 45" src="https://github.com/user-attachments/assets/ea4025ba-4897-47d2-add8-87506ec9e80a">

**Client Invoice Page**


**Important!** 
This module has been developed and tested on WHMCS 8.10.1 and the twenty-one template. If you are using a different version or template, manual adjustments to the module's code will be required.

**Comment by mrahmedinbox** [comment]
thanks a lot for help
