### ISSUE TITLE
Package and File Structure Inconsistent

### ISSUE THREAD

**Issue by ekiaadev** [Nikba-Creative-Studio/WHMCS-Gateway-Fees-Addon#3]
The documentation does not tally with what is packaged. The current package have all files in a folder that is not named as "gatewat_fees"

Kindly change the structure to;
/gateway_fees/
-gateway_fees.php
-/hooks/
--hooks.php

This way, documentation can say, "Upload to WHMCS root > Modules > Addon and extract"

Best regards

**Comment by Nikba-Creative-Studio** [comment]
Hi, thank you for the information. 
The Readme file has been updated to reflect the latest version of this module.
